### PR TITLE
Go 244/blank results visualization

### PR DESCRIPTION
**Pull request by crutch**
1. Rebased against main (was not able to run it due to database changes)
2. Fixed not being able to add filters from an empty state

### CODE REVIEW

**Comment by crutch** [comment]
image
image
image
image
image

**Comment by jsuchal** [comment]
@crutch tu vidim este mrte konfliktov

**Comment by crutch** [comment]
Aha, moja blbost. Zmenil som ten PR tak, aby bol voci main branch, nie voci tej povodnej blank results branch. Tu som musel rebasovat.

**Review by jsuchal — APPROVED** [review]

**Comment by luciajanikova** [comment]
@jsuchal nechceli sme sem zahrnut este aj notifikacie?

**Comment by jsuchal** [comment]
@luciajanikova dobra poznamka, pridajme issue

**Pull request merged**
